name: .NET Core

env:
  version: 1.0.${{ github.run_number }}
  nuget_source: https://nuget.pkg.github.com/amphasis/index.json

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore /p:Version=${{ env.version }}
    - name: Test
      env:
        SIMALAND_EMAIL: ${{ secrets.SIMALAND_EMAIL }} 
        SIMALAND_PASSWORD: ${{ secrets.SIMALAND_PASSWORD }} 
      run: dotnet test --no-restore --verbosity normal
    - name: Publish NuGet Package
      run: dotnet nuget push Amphasis.SimaLand.ApiClient/bin/Release/Amphasis.SimaLand.${{ env.version }}.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source ${{ env.nuget_source }}
